# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for verifiers/ct_synthesis_quality_v1/scripts/grade.py.

Three packs under fixtures/ drive these tests; they are regenerated by
conftest.py if absent.
"""

import importlib.util
import json
import shutil
from pathlib import Path

import nibabel as nib
import numpy as np

VERIFIER_DIR = Path(__file__).resolve().parents[1]
GRADE = VERIFIER_DIR / "scripts" / "grade.py"
spec = importlib.util.spec_from_file_location("grade", GRADE)
grade = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(grade)


def test_pass_pack_overall_pass():
    pack = VERIFIER_DIR / "fixtures" / "pass_pack"
    report = grade.grade(pack)
    assert report["target"]["skill_id"] == "nv_generate_ct_rflow"
    assert report["artifact_inventory"]["verdict"] == "pass"
    assert report["geometry_consistency"]["verdict"] == "pass"
    assert report["image_hu_plausibility"]["verdict"] == "pass"
    assert report["label_set_sanity"]["verdict"] == "pass"
    assert report["declared_anatomy_coverage"]["verdict"] == "pass"
    assert report["anatomy_hu_plausibility"]["verdict"] == "pass"
    assert report["overall"] == "pass"


def test_constant_image_pack_fails_hu_tier():
    pack = VERIFIER_DIR / "fixtures" / "constant_image_pack"
    report = grade.grade(pack)
    assert report["image_hu_plausibility"]["verdict"] == "fail"
    # geometry and labels are still fine
    assert report["geometry_consistency"]["verdict"] == "pass"
    assert report["label_set_sanity"]["verdict"] == "pass"
    assert report["overall"] == "fail"
    # the failed_checks should mention "constant image" or HU range
    failed = " ".join(report["image_hu_plausibility"]["failed_checks"]).lower()
    assert "constant" in failed or "hu<" in failed or "hu>" in failed


def test_out_of_range_label_pack_fails_label_tier():
    pack = VERIFIER_DIR / "fixtures" / "out_of_range_label_pack"
    report = grade.grade(pack)
    assert report["label_set_sanity"]["verdict"] == "fail"
    assert report["overall"] == "fail"
    failed = " ".join(report["label_set_sanity"]["failed_checks"]).lower()
    assert "out of vista3d range" in failed


def test_target_skill_mismatch_fails_overall(tmp_path):
    # Forge a pack whose manifest.json names a different skill — overall must fail
    # even if all tiers would pass.
    pack = tmp_path / "wrong_skill_pack"
    pack.mkdir()
    src = VERIFIER_DIR / "fixtures" / "pass_pack"
    for name in ("output.json", "validation_summary.json"):
        (pack / name).write_text((src / name).read_text())
    # Copy NIfTI pair so paths resolve.
    for child in src.iterdir():
        if child.suffix in (".gz",) or child.name.endswith(".nii.gz"):
            (pack / child.name).write_bytes(child.read_bytes())
    manifest = json.loads((src / "manifest.json").read_text())
    manifest["skill_id"] = "some_other_skill"
    (pack / "manifest.json").write_text(json.dumps(manifest))
    report = grade.grade(pack)
    assert report["overall"] == "fail"


def test_missing_declared_output_label_fails_declared_coverage(tmp_path):
    pack = tmp_path / "missing_declared_label_pack"
    src = VERIFIER_DIR / "fixtures" / "pass_pack"
    shutil.copytree(src, pack)
    output = json.loads((pack / "output.json").read_text())
    output["output"]["output_label_mapping"].append(
        {"anatomy": "heart", "maisi_label_id": 2, "output_label_id": 99}
    )
    (pack / "output.json").write_text(json.dumps(output))

    report = grade.grade(pack)

    assert report["declared_anatomy_coverage"]["verdict"] == "fail"
    assert report["declared_anatomy_coverage"]["missing_expected_output_label_ids"] == [99]
    assert report["overall"] == "fail"


def test_lung_lobe_soft_tissue_hu_fails_anatomy_hu_tier(tmp_path):
    pack = tmp_path / "bad_lung_lobe_hu_pack"
    pack.mkdir()
    affine = np.diag([1.5, 1.5, 2.0, 1.0])
    image = np.full((4, 4, 4), -900.0, dtype=np.float32)
    image[1:3, 1:3, 1:3] = 500.0
    image[0, 0, 0] = 300.0
    label = np.zeros((4, 4, 4), dtype=np.int16)
    label[1:3, 1:3, 1:3] = 1
    nib.save(nib.Nifti1Image(image, affine), str(pack / "sample_image.nii.gz"))
    nib.save(nib.Nifti1Image(label, affine), str(pack / "sample_label.nii.gz"))

    output = {
        "skill": "nv_generate_ct_rflow",
        "output": {
            "samples": [
                {
                    "image_path": "sample_image.nii.gz",
                    "label_path": "sample_label.nii.gz",
                }
            ],
            "output_label_mapping": [
                {
                    "anatomy": "right lung lower lobe",
                    "maisi_label_id": 32,
                    "output_label_id": 1,
                }
            ],
        },
    }
    (pack / "output.json").write_text(json.dumps(output))
    (pack / "manifest.json").write_text(json.dumps({"skill_id": "nv_generate_ct_rflow"}))
    (pack / "validation_summary.json").write_text(json.dumps({"overall_status": "passed"}))

    report = grade.grade(pack)

    assert report["label_set_sanity"]["verdict"] == "pass"
    assert report["declared_anatomy_coverage"]["verdict"] == "pass"
    assert report["anatomy_hu_plausibility"]["verdict"] == "fail"
    failed = " ".join(report["anatomy_hu_plausibility"]["failed_checks"]).lower()
    assert "right lung lower lobe" in failed
    assert "median hu" in failed
    assert report["overall"] == "fail"
